{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":" "},{"kind":"internalParam","text":"filepath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the sound."}]}]},{"name":"filePath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The path to the sound file on disk."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slothy\/slosound\/init(name:filepath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slothy\/slosound\/init(name:filepath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound\/init(name:filePath:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a sound given its name and path on"},{"type":"text","text":" "},{"type":"text","text":"disk."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(name:filePath:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SLOSound(im)initWithName:filePath:","modules":[{"name":"Slothy"}],"navigatorTitle":[{"kind":"identifier","text":"initWithName:filePath:"}]},"hierarchy":{"paths":[["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy","doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound"]]},"references":{"doc://asdfasdf.Slothy/documentation/Slothy/SLOSound/init(name:filePath:)":{"role":"symbol","title":"init(name:filePath:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a sound given its name and path on"},{"type":"text","text":" "},{"type":"text","text":"disk."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound\/init(name:filePath:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:filePath:"}],"url":"\/documentation\/slothy\/slosound\/init(name:filepath:)"},"doc://asdfasdf.Slothy/documentation/Slothy/SLOSound":{"role":"symbol","title":"SLOSound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSound"}],"abstract":[{"type":"text","text":"A sound that can be played."},{"type":"text","text":" "},{"type":"text","text":"Use an instance of this type to play a sound"},{"type":"text","text":" "},{"type":"text","text":"to the user in response to an action or"},{"type":"text","text":" "},{"type":"text","text":"event."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLOSound"}],"url":"\/documentation\/slothy\/slosound"},"doc://asdfasdf.Slothy/documentation/Slothy":{"role":"collection","title":"Slothy","abstract":[],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy","kind":"symbol","type":"topic","url":"\/documentation\/slothy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithName:filePath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:filePath:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"filePath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"filepath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound~1init(name:filePath:)\/title","value":"initWithName:filePath:"},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound~1init(name:filePath:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:filePath:"}]},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound\/title","value":"SLOSound"},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound\/fragments","value":[{"kind":"identifier","text":"SLOSound"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}