{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slothy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slothy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound","doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSoundPlayer"]},{"title":"Structures","identifiers":["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothView","doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothyApp"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"Slothy","title":"Slothy","symbolKind":"module","role":"collection","modules":[{"name":"Slothy"}]},"hierarchy":{"paths":[[]]},"references":{"doc://asdfasdf.Slothy/documentation/Slothy/SLOSoundPlayer":{"role":"symbol","title":"SLOSoundPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSoundPlayer"}],"abstract":[{"type":"text","text":"An object that plays sounds in an application"}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSoundPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLOSoundPlayer"}],"url":"\/documentation\/slothy\/slosoundplayer"},"doc://asdfasdf.Slothy/documentation/Slothy/SlothView":{"role":"symbol","title":"SlothView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SlothView"}],"abstract":[{"type":"text","text":"A view that displays a sloth."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SlothView"}],"url":"\/documentation\/slothy\/slothview"},"doc://asdfasdf.Slothy/documentation/Slothy/SlothyVersionString":{"role":"symbol","title":"SlothyVersionString","fragments":[{"kind":"identifier","text":"SlothyVersionString"}],"abstract":[{"type":"text","text":"Project version string for Slothy."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothyVersionString","kind":"symbol","type":"topic","url":"\/documentation\/slothy\/slothyversionstring"},"doc://asdfasdf.Slothy/documentation/Slothy":{"role":"collection","title":"Slothy","abstract":[],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy","kind":"symbol","type":"topic","url":"\/documentation\/slothy"},"doc://asdfasdf.Slothy/documentation/Slothy/SlothyApp":{"role":"symbol","title":"SlothyApp","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SlothyApp"}],"abstract":[{"type":"text","text":"The Slothy application."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothyApp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SlothyApp"}],"url":"\/documentation\/slothy\/slothyapp"},"doc://asdfasdf.Slothy/documentation/Slothy/SlothyVersionNumber":{"role":"symbol","title":"SlothyVersionNumber","fragments":[{"kind":"identifier","text":"SlothyVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for Slothy."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothyVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/slothy\/slothyversionnumber"},"doc://asdfasdf.Slothy/documentation/Slothy/SLOSound":{"role":"symbol","title":"SLOSound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSound"}],"abstract":[{"type":"text","text":"A sound that can be played."},{"type":"text","text":" "},{"type":"text","text":"Use an instance of this type to play a sound"},{"type":"text","text":" "},{"type":"text","text":"to the user in response to an action or"},{"type":"text","text":" "},{"type":"text","text":"event."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLOSound"}],"url":"\/documentation\/slothy\/slosound"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound","doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSoundPlayer"]},{"title":"Variables","identifiers":["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothyVersionNumber","doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SlothyVersionString"]}]},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSoundPlayer\/title","value":"SLOSoundPlayer"},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSoundPlayer\/fragments","value":[{"kind":"identifier","text":"SLOSoundPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound\/title","value":"SLOSound"},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound\/fragments","value":[{"kind":"identifier","text":"SLOSound"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}