{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSoundPlayer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slothy\/slosoundplayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slothy\/slosoundplayer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/asdfasdf.Slothy\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/asdfasdf.Slothy\/objc(pl)NSObject","doc:\/\/asdfasdf.Slothy\/s7CVarArgP","doc:\/\/asdfasdf.Slothy\/s28CustomDebugStringConvertibleP","doc:\/\/asdfasdf.Slothy\/s23CustomStringConvertibleP","doc:\/\/asdfasdf.Slothy\/SQ","doc:\/\/asdfasdf.Slothy\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSoundPlayer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that plays sounds in an application"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSoundPlayer"}],"title":"SLOSoundPlayer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SLOSoundPlayer","modules":[{"name":"Slothy"}],"navigatorTitle":[{"kind":"identifier","text":"SLOSoundPlayer"}]},"hierarchy":{"paths":[["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy"]]},"references":{"doc://asdfasdf.Slothy/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/asdfasdf.Slothy\/s28CustomDebugStringConvertibleP"},"doc://asdfasdf.Slothy/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/asdfasdf.Slothy\/s7CVarArgP"},"doc://asdfasdf.Slothy/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/asdfasdf.Slothy\/SH"},"doc://asdfasdf.Slothy/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/asdfasdf.Slothy\/s23CustomStringConvertibleP"},"doc://asdfasdf.Slothy/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/asdfasdf.Slothy\/SQ"},"doc://asdfasdf.Slothy/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/asdfasdf.Slothy\/objc(pl)NSObject"},"doc://asdfasdf.Slothy/documentation/Slothy/SLOSoundPlayer":{"role":"symbol","title":"SLOSoundPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSoundPlayer"}],"abstract":[{"type":"text","text":"An object that plays sounds in an application"}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSoundPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLOSoundPlayer"}],"url":"\/documentation\/slothy\/slosoundplayer"},"doc://asdfasdf.Slothy/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/asdfasdf.Slothy\/objc(cs)NSObject"},"doc://asdfasdf.Slothy/documentation/Slothy":{"role":"collection","title":"Slothy","abstract":[],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy","kind":"symbol","type":"topic","url":"\/documentation\/slothy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SLOSoundPlayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SLOSoundPlayer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SLOSoundPlayer"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSoundPlayer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSoundPlayer\/title","value":"SLOSoundPlayer"},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSoundPlayer\/fragments","value":[{"kind":"identifier","text":"SLOSoundPlayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}