{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSound"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/slothy\/slosound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/slothy\/slosound"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/asdfasdf.Slothy\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/asdfasdf.Slothy\/objc(pl)NSObject","doc:\/\/asdfasdf.Slothy\/s7CVarArgP","doc:\/\/asdfasdf.Slothy\/s28CustomDebugStringConvertibleP","doc:\/\/asdfasdf.Slothy\/s23CustomStringConvertibleP","doc:\/\/asdfasdf.Slothy\/SQ","doc:\/\/asdfasdf.Slothy\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A sound that can be played."},{"type":"text","text":" "},{"type":"text","text":"Use an instance of this type to play a sound"},{"type":"text","text":" "},{"type":"text","text":"to the user in response to an action or"},{"type":"text","text":" "},{"type":"text","text":"event."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSound"}],"title":"SLOSound","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SLOSound","modules":[{"name":"Slothy"}],"navigatorTitle":[{"kind":"identifier","text":"SLOSound"}]},"hierarchy":{"paths":[["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound\/init(name:filePath:)"]}],"references":{"doc://asdfasdf.Slothy/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/asdfasdf.Slothy\/s7CVarArgP"},"doc://asdfasdf.Slothy/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/asdfasdf.Slothy\/SH"},"doc://asdfasdf.Slothy/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/asdfasdf.Slothy\/s28CustomDebugStringConvertibleP"},"doc://asdfasdf.Slothy/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/asdfasdf.Slothy\/objc(pl)NSObject"},"doc://asdfasdf.Slothy/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/asdfasdf.Slothy\/s23CustomStringConvertibleP"},"doc://asdfasdf.Slothy/documentation/Slothy/SLOSound":{"role":"symbol","title":"SLOSound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSound"}],"abstract":[{"type":"text","text":"A sound that can be played."},{"type":"text","text":" "},{"type":"text","text":"Use an instance of this type to play a sound"},{"type":"text","text":" "},{"type":"text","text":"to the user in response to an action or"},{"type":"text","text":" "},{"type":"text","text":"event."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SLOSound"}],"url":"\/documentation\/slothy\/slosound"},"doc://asdfasdf.Slothy/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/asdfasdf.Slothy\/SQ"},"doc://asdfasdf.Slothy/documentation/Slothy":{"role":"collection","title":"Slothy","abstract":[],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy","kind":"symbol","type":"topic","url":"\/documentation\/slothy"},"doc://asdfasdf.Slothy/documentation/Slothy/SLOSound/init(name:filePath:)":{"role":"symbol","title":"init(name:filePath:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a sound given its name and path on"},{"type":"text","text":" "},{"type":"text","text":"disk."}],"identifier":"doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound\/init(name:filePath:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:filePath:"}],"url":"\/documentation\/slothy\/slosound\/init(name:filepath:)"},"doc://asdfasdf.Slothy/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/asdfasdf.Slothy\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SLOSound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SLOSound"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SLOSound"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/asdfasdf.Slothy\/documentation\/Slothy\/SLOSound\/init(name:filePath:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SLOSound"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound\/title","value":"SLOSound"},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound\/fragments","value":[{"kind":"identifier","text":"SLOSound"}]},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound~1init(name:filePath:)\/title","value":"initWithName:filePath:"},{"op":"replace","path":"\/references\/doc:~1~1asdfasdf.Slothy~1documentation~1Slothy~1SLOSound~1init(name:filePath:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:filePath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}